apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: max@maxphillips.dev
    privateKeySecretRef:
      name: cluster-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: max@maxphillips.dev
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
