apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    app: podinfo
  ports:
    - name: websecure
      port: 80
      targetPort: 9898
      protocol: TCP
