apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
  namespace: ingress
spec:
  acme:
    email: max@maxphillips.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-api-token-secret
    solvers:
      - dns01:
          cloudflare:
            email: max@maxphillips.dev
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
