apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.6.5
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 1m
  values:
    hostname: rancher.memp.dev
    ingress:
      tls:
        source: letsEncrypt
      letsEncrypt.email: max@maxphillips.dev
      letsEncrypt.ingress.class: traefik
    replicaCount: 1
